language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi

script:
  - vendor/bin/kahlan --coverage=4 --reporter=verbose

notifications:
  email: false

matrix:
  fast_finish: true